databases:
  - name: platypus_db
    databaseName: platypus_db
    user: platypus_user

services:
  - type: web
    name: platypus-ecommerce
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: 'platypus_ecommerce.wsgi.application'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: platypus_db
          property: connectionString
      - key: 'django-insecure-rs6gx*h)egp%g6t@j0@82p3x#1lhf=t%hx6b%ia13o6%!3@lqn'
        generateValue: true
      - key: RENDER
        value: true
      - key: PYTHON_VERSION
        value: 3.8
